kind: Template
apiVersion: v1
metadata:
  name: ${APP_NAME}-build-deploy-template
labels:
  app: ${APP_NAME}
objects:
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      labels:
        build: ${APP_NAME}
      name: ${APP_NAME}
    spec:
      failedBuildsHistoryLimit: 5
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: app-main:latest
      postCommit: {}
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 500m
          memory: 512Mi
      runPolicy: Serial
      source:
        binary: {}
        type: Binary
      strategy:
        sourceStrategy:
          from:
            kind: DockerImage
            name: registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift:latest
        type: Source
      successfulBuildsHistoryLimit: 5
      triggers:
        - github:
            secret: ${GITHUB_SECRET}
          type: GitHub
        - generic:
            secret: ${SCM_GENERIC}
          type: Generic

  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      name: ${APP_NAME}
    spec:
      lookupPolicy:
        local: false
      tags:
        - from:
            kind: DockerImage
            name: ${APP_NAME}
          generation: 2
          importPolicy: {}
          name: latest
          referencePolicy:
            type: Source
parameters:
  - description: name of the app
    name: APP_NAME
    required: true
  - description: size of the volume
    name: VOLUME_SIZE
    value: 1Mi
    required: true
  - description : name of the storageclass
    name: STORAGE_CLASS
    value: glusterfs-ocs
    required: true
  - description: valu for github secret
    name: GITHUB_SECRET
    from: '[A-Z0-9]{8}'
    generate: expression
  - description: valu for generic scm secret
    name: SCM_GENERIC
    from: '[A-Z0-9]{8}'
    generate: expression
    
