apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: app-front
  name: app-front
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: app-front:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: openjdk18-openshift:latest
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: TFZIo0sDMTOTVSPTGlz8
    type: GitHub
  - generic:
      secret: vCliXK_1MDOqCZE-mLgM
    type: Generic
