apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: app-main
  name: app-main
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: app-main:latest
  postCommit: {}
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 256Mi
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: openjdk18-openshift:latest
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
    - github:
        secret: oGwD1LKaFKTnIkvf3z_l
      type: GitHub
    - generic:
        secret: DB6VX76yVm30K_pZ8nA0
      type: Generic
