apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: app-main
  name: app-main
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: app-main
    weight: 100
  wildcardPolicy: None
